---
name: Setup Ansible environment
description: Install uv, Python, create venv, and install pip/galaxy dependencies
inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.14"
  install-yq:
    description: "Install yq (apt) for molecule"
    required: false
    default: "false"
  install-galaxy-requirements:
    description: "Run ansible-galaxy install -r requirements.yml"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        version: "0.10.0"
        enable-cache: true

    - name: Set up Python
      run: uv python install ${{ inputs.python-version }}
      shell: bash

    - name: Install yq
      if: inputs.install-yq == 'true'
      run: sudo apt-get update && sudo apt-get install -y yq
      shell: bash

    - name: Install dependencies
      run: |
        uv -q venv --allow-existing --seed .venv
        . .venv/bin/activate
        uv -q pip install -r requirements.txt
      shell: bash

    - name: Install Galaxy requirements
      if: inputs.install-galaxy-requirements == 'true'
      run: |
        . .venv/bin/activate
        ansible-galaxy install -r requirements.yml
      shell: bash
